### ISSUE TITLE
Can't run on ubuntu 14.04.1

### ISSUE THREAD

**Issue by jgribonvald** [projecthamster/unity-indicator#1]
here is the error 
./hamster-indicator
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:40: Warning: specified class size for type 'PyGtkGenericCellRenderer' is smaller than the parent type's 'GtkCellRenderer' class size
  from gtk import _gtk
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
Erreur de segmentation (core dumped)

How to solve that ?

**Comment by einmalfel** [comment]
IIRC I got those messages when I ran hamster-indicator from git with hamster from ubuntu package repository. Seems they are incompatible. Try installing hamster from [here](https://launchpad.net/~dylanmccall/+archive/ubuntu/hamster-time-tracker-git-daily)

**Comment by jgribonvald** [comment]
Ok,
But to run daily builds I had the bug listed on https://github.com/projecthamster/hamster/issues/137 and to solve it I installed gir1.2-gconf-2.0 package. 

Also now the UI is different and not so easy than before to define automatically times of next activities

**Comment by nchachereau** [comment]
Indeed, the unity-indicator is meant to work with the latest Hamster, and not with the stable version. I updated the README to clarify this.

Regarding the UI, Hamster's creator changed it a lot, and then his priorities changed and he isn't maintaining the project anymore. A few volunteers tried to take over, but it is difficult. I am not sure I like the new UI that much either... but that's a different issue.

I am closing this issue.
