### ISSUE TITLE
Add autocompletion support

### ISSUE THREAD

**Issue by TeXtnik** [projecthamster/unity-indicator#3]
Adding autocompletion for activities, categories and tags will be a big step. Having to write all, not only needs more time, but also allows typos to appear, creating new acitvities or tags that them should be removed by hand.

**Comment by nchachereau** [comment]
The unity-indicator uses the main hamster interface. Unless I misunderstand your comment, you should report your bug on the [main repository](https://github.com/projecthamster/hamster), where the window to add activities resides. When you do so, you may want to provide some additional information, for instance what version of Hamster you are using. For me at least, auto-completion works with the current trunk. It works in a limited way, which could definitely be improved (it does not search all activities, you have to type the beginning of the activity's name, etc.)

Or maybe you are using Gnome 3, and thus Hamster's [shell extension](https://github.com/projecthamster/shell-extension)? As I do not use it, I don't know whether auto-completion works or not.
