### ISSUE TITLE
"New activity" doesn't accept activity description

### ISSUE THREAD

**Issue by zunbeltz** [projecthamster/unity-indicator#7]
I have installed hamster and unity-indicator from git (last version). When I add a activity description like "10:00 10:30 Read@Day to Day#home, The hitchhiker's guide to the Galaxy", the description part is not showing in the Overview. If I open the activity again, it reads like "10:00 10:30 Read@Day to Day#home," (with the comma). 

Activities recorded long ago, before unity, with the applet, show the description correctly. I guess that the "New activity" dialog is somehow discarding the description and not storing in the database.

**Comment by nchachereau** [comment]
Hello, thanks a lot for your bug report!

I think your answer applies to Hamster itself and not to the indicator. The indicator is only responsible for the menu. The Add activity window and the Overview are part of the main Hamster project. You might want to report your problem there, but please be aware that the project is overgoing major changes right now.

Closing this, feel free to complain if I misunderstood your problem.

Regards, Nicolas
