### ISSUE TITLE
Getting in touch...

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/unity-indicator#8]
@nchachereau  I am sorry to misuse the tracker like this, but I wanted to make sure to reach you :)
I do not mean to bother you but as my mail a month ago went unanswered I was not sure if that was deliberate or not. So I do hope you can overlook this rather drastic way to get in touch...
So i guess my question is: Did my mail get to you?

Thanks for your time, Eric.

**Comment by nchachereau** [comment]
Hi Eric, sorry about that. Just answered you. Thanks for reminding me! Nicolas
